---
inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
  - Gemfile
  - Rakefile
  - 'test/**/*'
  - 'examples/plugins/train-*/test/**/*'
  - 'vendor/**/*'
Style/Documentation:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: true
Style/Encoding:
  Enabled: false
Style/HashSyntax:
  Enabled: true
Layout/LineLength:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Style/NumericLiterals:
  MinDigits: 10
Metrics/ModuleLength:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': ()
    '%q': '{}'
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '{}'
    '%W': ()
    '%x': ()
Layout/HashAlignment:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/Not:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/NegatedIf:
  Enabled: false
Style/UnlessElse:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SignalException:
  Enabled: false
